# Kilink configuration for production environment

server_host: linkode.org
db_engine: postgresql+psycopg2://{user}:{pass}@localhost/kilink
db_auth_config: configs/db_auth.txt
log_directory: /home/kilink/logs/production/
version_file: /home/kilink/project/production/version.txt
max_payload: 10240
